### ISSUE TITLE
fix notification when clicking the copy button

### ISSUE THREAD

**Issue by M3NIX** [M3NIX/sigmaio#5]
Remove https://github.com/M3NIX/sigmaio/blob/main/static/js/index.js#L33:L39 and implement an alert message with semantic UI e.g. 
https://semantic-ui.com/collections/message.html

**Comment by upendrasahni** [comment]
Hey @M3NIX , Can you assign this issue to me? I would love to work on this issue.

**Comment by M3NIX** [comment]
implemented with #23
